# Generated by Django 5.0.6 on 2025-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=56)),
                ("slug", models.SlugField(max_length=56)),
                ("is_menu", models.BooleanField(default=True)),
            ],
        ),
    ]
