# Generated by Django 5.0.6 on 2025-04-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Sarlavhasi")),
                ("short_desc", models.TextField(verbose_name="Wisqacha")),
                ("description", models.TextField(verbose_name="Toliq")),
                ("rasm", models.ImageField(upload_to="new/")),
                ("rasm2", models.ImageField(blank=True, null=True, upload_to="new/")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("tegs", models.CharField(blank=True, max_length=512, null=True)),
                ("view", models.IntegerField(default=1)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.category"
                    ),
                ),
            ],
        ),
    ]
