# Generated by Django 5.0.6 on 2025-04-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_contact_sub_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "Komment", "verbose_name_plural": "Kommentlar"},
        ),
    ]
