# Generated by Django 5.0.6 on 2025-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_comments_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=56, unique=True),
        ),
    ]
