# Generated by Django 5.0.6 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=56, unique=True),
        ),
    ]
