# Generated by Django 5.0.6 on 2025-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
