# Generated by Django 5.0.6 on 2025-05-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_alter_new_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="massege",
            new_name="massage",
        ),
    ]
